- name: install required software
  package: name={{ item }} state=present
  with_items:
    - nginx
    - postgresql
    - odbc-postgresql
    - python3-pyodbc
    - python3-psycopg2
    - python3-gnupg
    - python-psycopg2
    - python3-yaml
    - python3-flask
    - git

- name: install imagebuilder dependencies
  package: name={{ item }} state=present
  with_items:
    - time
    - subversion
    - build-essential
    - libncurses5-dev
    - zlib1g-dev
    - gawk
    - git
    - ccache
    - gettext
    - libssl-dev
    - xsltproc
    - wget
    - unzip
    - python

- name: ensure database is created
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
  postgresql_db:
    name: "{{ database_name }}"

- name: ensure user has access to database
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
  postgresql_user:
    db: "{{ database_name }}"
    name: "{{ database_user }}"
    password: "{{ database_pass }}"
    priv: ALL

- name: ensure user does not have unnecessary privilege
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
  postgresql_user:
    name: "{{ database_user }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB

- name: clone server git repo
  git:
    repo: 'https://github.com/aparcar/attendedsysupgrade-server.git'
    dest: "{{ server_dir }}"
    version: meta-builder

- name: init database
  become_user: postgres
  vars:
      ansible_ssh_pipelining: true
  postgresql_db:
    name: "{{ database_name }}"
    state: restore
    target: "{{ server_dir }}/utils/tables.sql"
