# server
dev: False
sign_images: True
server: "http://localhost:5000"
server_user: root
server_dir: /vagrant

# database
database_type: PostgreSQL Unicode
database_address: localhost
database_name: attendedsysupgrade
database_user: postgres
database_pass: changeme
database_port: 5432

# folder
imagebuilder_folder: imagebuilder
distro_folder: distributions
download_folder: download
tempdir: /tmp
keys_private: keys
keys_public: server/static/keys
