---
distro_alias: LEDE
releases:
  - "17.01.0"
  - "17.01.1"
  - "17.01.2"
  - "17.01.3"
  - "17.01.4"
  - "17.01.5"
vanilla:
  - luci
targets_url: https://downloads.lede-project.org/releases/
board_rename:
  nanostation-m: ubnt-nano-m
  nanostation-m-xw: ubnt-nano-m-xw
  loco-m: ubnt-loco-m
  loco-m-xw: ubnt-loco-m-xw
  tl-wdr3500: tl-wdr3500-v1
  tl-wdr4300: tl-wdr4300-v1
  tl-wr741: tl-wr741-v1
