---
distro_alias: "LibreMesh"
parent_distro: "lede"
parent_version: "17.01.4"
versions:
  - "17.06"
  - "18.06.0"
  - "snapshots"
  - "snapshots-dev"
repos: |
  src/gz reboot_core http://downloads.lede-project.org/releases/{{ ib_version }}/targets/{{ target }}/{{ subtarget }}/packages
  src/gz reboot_base http://downloads.lede-project.org/releases/{{ ib_version }}/packages/{{ pkg_arch }}/base
  src/gz reboot_luci http://downloads.lede-project.org/releases/{{ ib_version }}/packages/{{ pkg_arch }}/luci
  src/gz reboot_packages http://downloads.lede-project.org/releases/{{ ib_version }}/packages/{{ pkg_arch }}/packages
  src/gz reboot_telephony http://downloads.lede-project.org/releases/{{ ib_version }}/packages/{{ pkg_arch }}/telephony
  src imagebuilder file:packages
  src/gz libremesh http://repo.libremesh.org/releases/{{ version }}/packages/{{ pkg_arch }}/libremesh
  src/gz libremap http://repo.libremesh.org/releases/{{ version }}/packages/{{ pkg_arch }}/libremap
  src/gz limeui http://repo.libremesh.org/releases/{{ version }}/packages/{{ pkg_arch }}/limeui
  src/gz lm_routing http://repo.libremesh.org/releases/{{ version }}/packages/{{ pkg_arch }}/routing
  src/gz lm_profiles http://repo.libremesh.org/network-profiles/
active_targets:
    - ar71xx/generic
    - ramips/rt305x
    - ramips/rt3883
    - ramips/mt7620
    - ramips/mt7621
    - ramips/mt7628
    - ramips/mt7688
    - lantiq/xrx200
    - lantiq/xway
    - x86/generic
    - x86/64
    - x86/geode
    - mvebu/generic
    - ipq806x/generic
    - brcm2708/bcm2708
    - brcm2708/bcm2709
    - brcm2708/bcm2710
    - octeon/generic
    - sunxi/generic
    - mediatek/generic
    - arm64/generic
    - armvirt/generic
distro_description: >
  LibreMesh is a modular framework for creating OpenWrt-based firmwares for
  wireless mesh nodes. Several communities around the world use LibreMesh as the
  foundation of their local mesh firmwares.

